source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'puma'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'

gem 'bootstrap-sass', '~> 3.3.5'

group :development, :test do
  gem 'pry-rails'
  gem 'web-console', '~> 2.0'
end
